In [ ]:
import pandas as pd

data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 
        'year' : [2000, 2001, 2002, 2001, 2002],
        'pop' : [1.5, 1.7, 3.6, 2.4, 2.9]}

pd.DataFrame(data)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [ ]:
a = pd.DataFrame(data, columns = ['pop', 'year', 'state'], 
                index = ['one', 'two', 'three', 'four', 'five'])

In [ ]:
a['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [ ]:
a.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [ ]:
a['debt'] = 16.5
a

       pop  year   state  debt
one    1.5  2000    Ohio  16.5
two    1.7  2001    Ohio  16.5
three  3.6  2002    Ohio  16.5
four   2.4  2001  Nevada  16.5
five   2.9  2002  Nevada  16.5

In [ ]:
a['debt'] = pd.Series([-1.2, -3, -2], index = ['four', 'two', 'one'])
a

       pop  year   state  debt
one    1.5  2000    Ohio  -2.0
two    1.7  2001    Ohio  -3.0
three  3.6  2002    Ohio   NaN
four   2.4  2001  Nevada  -1.2
five   2.9  2002  Nevada   NaN

In [ ]:
a['eastern'] = a.debt
a

       pop  year   state  debt  eastern
one    1.5  2000    Ohio  -2.0     16.5
two    1.7  2001    Ohio  -3.0     16.5
three  3.6  2002    Ohio   NaN     16.5
four   2.4  2001  Nevada  -1.2     16.5
five   2.9  2002  Nevada   NaN     16.5

In [ ]:
del a['eastern']
a

       pop  year   state  debt
one    1.5  2000    Ohio  -2.0
two    1.7  2001    Ohio  -3.0
three  3.6  2002    Ohio   NaN
four   2.4  2001  Nevada  -1.2
five   2.9  2002  Nevada   NaN

In [ ]:
#Exercise 1
a = pd.DataFrame({'Nevada' : [2.4, 2.9, None], 'Ohio': [3.2, 2.1, 1.9]}, 
                 index = [2001, 2003, 2002])
a

      Nevada  Ohio
2001     2.4   3.2
2003     2.9   2.1
2002     NaN   1.9

In [ ]:
#Exercise 2
a['Utah'] = [3.3, 3.1, 3.2]
a

      Nevada  Ohio  Utah
2001     2.4   3.2   3.3
2003     2.9   2.1   3.1
2002     NaN   1.9   3.2

In [ ]:
#사전 이용 인덱스 및 데이터프레임 생성
a = pd.DataFrame({'Nevada' : {2001 : 2.4, 2003 : 2.9}, 
                  'Ohio' : {2003 : 2.1, 2002 : 1.9, 2001 : 3.2}})
a

#{column : {index : values}} 형태

      Nevada  Ohio
2001     2.4   3.2
2003     2.9   2.1
2002     NaN   1.9

In [ ]:
pd.DataFrame(a, columns = ['Nevada'])

      Nevada
2001     2.4
2003     2.9
2002     NaN

In [ ]:
pd.DataFrame(a, index = [2003, 2002])

      Nevada  Ohio
2003     2.9   2.1
2002     NaN   1.9

In [ ]:
a.T

        2001  2003  2002
Nevada   2.4   2.9   NaN
Ohio     3.2   2.1   1.9

In [ ]:
a.index

Int64Index([2001, 2003, 2002], dtype='int64')

In [ ]:
type(a.values)

numpy.ndarray

In [ ]:
a.index.name = 'year'
a

      Nevada  Ohio
year
2001     2.4   3.2
2003     2.9   2.1
2002     NaN   1.9

In [ ]:
a.columns.name = 'state'
a

state  Nevada  Ohio
year
2001      2.4   3.2
2003      2.9   2.1
2002      NaN   1.9

In [ ]:
a = [1, 2, 3]
b = [4, 5.0, 6]
c = [True, False, True]
d = ['A', 'B', 'C']
DF = pd.DataFrame([a, b, c, d])
DF

      0      1     2
0     1      2     3
1     4    5.0     6
2  True  False  True
3     A      B     C

In [ ]:
# Indexing은 column(열) data 출력
DF[1]

0        2
1      5.0
2    False
3        B
Name: 1, dtype: object

In [ ]:
# Slicing은 index(행) data 출력
DF[0:1]

   0  1  2
0  1  2  3

In [ ]:
DF.index = ['a', 'b', 'c', 'd']
DF.columns = ['A', 'B', 'C']
DF

      A      B     C
a     1      2     3
b     4    5.0     6
c  True  False  True
d     A      B     C

In [ ]:
DF['B']

a        2
b      5.0
c    False
d        B
Name: B, dtype: object

In [ ]:
'''
a = [1, 2, 3]
b = [4, 5.0, 6]
c = [True, False, True]
d = ['A', 'B', 'C']
'''
DF = pd.DataFrame({'A' : a, 'B' : b, 'C' : c, 'D' : d}, index = list('abc'))
DF

   A    B      C  D
a  1  4.0   True  A
b  2  5.0  False  B
c  3  6.0   True  C

In [ ]:
#.loc : index, column name 기준으로 값을 뽑아냄
DF.loc['b', 'A']

2

In [ ]:
#.iloc : 행, 열 번호 기준으로 값을 뽑아냄
DF.iloc[2, 3]

'C'

In [ ]:
# .loc[ : , : ] - dataframe 출력
DF.loc[['c', 'a'], ['D', 'D', 'A']]

   D  D  A
c  C  C  3
a  A  A  1

In [ ]:
# .iloc [ : , : ] - dataframe 출력
DF.iloc[1:2, 1:2]

     B
b  5.0

In [ ]:
DF

   A    B      C  D
a  1  4.0   True  A
b  2  5.0  False  B
c  3  6.0   True  C

In [ ]:
print(DF.A, end = '\n')
print(type(DF.A)) #DF.index 로 출력하면 Series 형태로 변수가 바뀜

a    1
b    2
c    3
Name: A, dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
DF.A[0]

1

In [ ]:
import pandas as pd
a = [1, 'apple', 13]
b = [2, 'apple', 15]
c = [1, 'orange', 21]
d = [2, 'orange', 12]
DF = pd.DataFrame([a, b, c, d], 
                  columns = ['Months', 'Fruits', 'Ratio'], index = range(1, 5))
DF

   Months  Fruits  Ratio
1       1   apple     13
2       2   apple     15
3       1  orange     21
4       2  orange     12

In [ ]:
DF.index = ['one', 'two', 'three', 'four']
DF2 = DF.loc[:, ['Ratio', 'Fruits']]
DF2

       Ratio  Fruits
one       13   apple
two       15   apple
three     21  orange
four      12  orange