In [ ]:
# 연습문제 1
import pandas as pd
a = pd.DataFrame({'Nevada' : [2.4, 2.9, None], 'Ohio': [3.2, 2.1, 1.9]}, index = [2001, 2003, 2002])
a

      Nevada  Ohio
2001     2.4   3.2
2003     2.9   2.1
2002     NaN   1.9

In [ ]:
# 연습문제 2
a['Utah'] = [3.3, 3.1, 3.2]
a

      Nevada  Ohio  Utah
2001     2.4   3.2   3.3
2003     2.9   2.1   3.1
2002     NaN   1.9   3.2

In [ ]:
#연습문제 1

import pandas as pd
a = [1, 'apple', 13]
b = [2, 'apple', 15]
c = [1, 'orange', 21]
d = [2, 'orange', 12]
DF = pd.DataFrame([a, b, c, d], columns = ['Month', 'Fruits', 'Ratio'], index = range(1, 5))
DF

   Month  Fruits  Ratio
1      1   apple     13
2      2   apple     15
3      1  orange     21
4      2  orange     12

In [ ]:
import pandas as pd
DF = pd.DataFrame({'Month' : [1, 2, 1, 2], 'Fruits' : ['apple', 'apple', 'orange', 'orange'], 'Ratio' : [13, 15, 21, 12]}, index = range(1, 5))
DF

   Month  Fruits  Ratio
1      1   apple     13
2      2   apple     15
3      1  orange     21
4      2  orange     12

In [ ]:
#연습문제2
DF2 = DF
DF2.index = ['one', 'two', 'three', 'four']
DF2 = DF2.loc[:, ['Ratio', 'Fruits']]
DF2

       Ratio  Fruits
one       13   apple
two       15   apple
three     21  orange
four      12  orange